{% set name = "compas_rrc" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compas_rrc-{{ version }}.tar.gz
  sha256: 5e47de1072bc505500b25232b1925449fe73aa6d4469735d512b046cecaec7be

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - compas_fab >=1,<2
    - roslibpy >=1.1
    - python >={{ python_min }}

test:
  imports:
    - compas_rrc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/compas-rrc/compas_rrc
  summary: 'COMPAS RRC: Online control for ABB robots over a simple-to-use Python interface.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
    - fleischp
